import { StyleSheet, Platform, StatusBar } from 'react-native';
import { C } from '../constants/colors';
import { W, H } from '../constants/data';

export const feedStyles = StyleSheet.create({
  container:           { width: W, height: H, backgroundColor: C.bg },
  heroImage:           { position: 'absolute', top: 0, left: 0, right: 0, height: H * 0.58 },
  fadeOverlay:         { position: 'absolute', top: H * 0.28, left: 0, right: 0, height: H * 0.72 },
  content:             { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 22, paddingBottom: Platform.OS === 'ios' ? 36 : 24 },
  liveBadge:           { flexDirection: 'row', alignItems: 'center', gap: 5, marginBottom: 10 },
  liveBadgeText:       { fontSize: 9, fontWeight: '700', letterSpacing: 1.8, color: C.rose },
  metaRow:             { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12, flexWrap: 'wrap' },
  catBadge:            { borderRadius: 22, paddingHorizontal: 12, paddingVertical: 4, borderWidth: 1 },
  catText:             { fontSize: 9, fontWeight: '700', letterSpacing: 1.3 },
  scoreBarWrap:        { width: 44, height: 3, backgroundColor: 'rgba(255,255,255,.1)', borderRadius: 2 },
  scoreFill:           { height: '100%', borderRadius: 2 },
  scoreLabel:          { fontSize: 10, color: 'rgba(255,255,255,.38)' },
  srcLabel:            { fontSize: 10, color: 'rgba(255,255,255,.3)' },
  headline:            { fontSize: 22, fontWeight: '700', color: C.white, lineHeight: 30, marginBottom: 10, letterSpacing: -0.3 },
  summary:             { fontSize: 14, color: 'rgba(238,240,255,.5)', lineHeight: 22, marginBottom: 14 },
  tagPill:             { backgroundColor: 'rgba(255,255,255,.08)', borderWidth: 1, borderColor: 'rgba(255,255,255,.12)', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 4 },
  tagPillText:         { fontSize: 10, color: 'rgba(255,255,255,.45)' },
  actionRow:           { flexDirection: 'row', gap: 10 },
  saveBtn:             { backgroundColor: 'rgba(255,255,255,.08)', borderWidth: 1, borderColor: 'rgba(255,255,255,.14)', borderRadius: 26, paddingHorizontal: 20, paddingVertical: 13, justifyContent: 'center' },
  saveBtnText:         { color: 'rgba(255,255,255,.65)', fontSize: 13 },
  deepBtn:             { flex: 1, borderRadius: 26, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(91,79,232,.50)' },
  deepBtnGrad:         { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, paddingVertical: 13 },
  deepBtnText:         { color: '#c4beff', fontSize: 13, fontWeight: '500' },
  topBarGradient:      { position: 'absolute', top: 0, left: 0, right: 0, height: 120 },
  topBar:              { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight + 8 : 10, paddingBottom: 10 },
  morningBriefBtn:     { backgroundColor: 'rgba(245,166,35,0.14)', borderWidth: 1, borderColor: 'rgba(245,166,35,0.4)', borderRadius: 22, paddingHorizontal: 14, paddingVertical: 8 },
  morningBriefBtnText: { color: C.gold, fontSize: 12, fontWeight: '600' },
  loadMoreFooter:      { height: H, justifyContent: 'center', alignItems: 'center', backgroundColor: C.bg, gap: 4 },
  catBarScroll:        { maxHeight: 44 },
  catBarContent:       { paddingHorizontal: 16, paddingVertical: 6, gap: 8, alignItems: 'center' },
  catChip:             { borderRadius: 16, paddingHorizontal: 14, paddingVertical: 6 },
  catChipActive:       { backgroundColor: '#2563eb' },
  catChipInactive:     { backgroundColor: 'transparent', borderWidth: 1, borderColor: '#374151' },
  catChipText:         { fontSize: 12, fontWeight: '600', letterSpacing: 0.2 },
  catChipTextActive:   { color: '#ffffff' },
  catChipTextInactive: { color: '#9ca3af' },
});