import { StyleSheet } from 'react-native';
import { C } from '../constants/colors';

export const styles = StyleSheet.create({
  screen:           { flex: 1, backgroundColor: C.bg },
  loadingScreen:    { flex: 1, backgroundColor: C.bg, alignItems: 'center', justifyContent: 'center' },
  loadingText:      { color: C.muted, fontSize: 13, letterSpacing: 0.5 },
  retryBtnFull:     { backgroundColor: C.indigo, borderRadius: 24, paddingVertical: 12, paddingHorizontal: 32 },
  retryBtnText:     { color: '#fff', fontSize: 14, fontWeight: '600' },
  infoBlock:        { backgroundColor: 'rgba(255,255,255,.03)', borderWidth: 1, borderColor: 'rgba(255,255,255,.07)', borderRadius: 12, padding: 14, marginBottom: 11 },
  fieldLabel:       { fontSize: 9, fontWeight: '700', letterSpacing: 1.6, marginBottom: 8 },
  bodyText:         { fontSize: 13, color: 'rgba(238,240,255,.52)', lineHeight: 21 },
  importanceBlock:  { backgroundColor: 'rgba(91,79,232,.08)', borderWidth: 1, borderColor: 'rgba(91,79,232,.26)', borderRadius: 10, padding: 13 },
  importanceText:   { fontSize: 12, color: '#c4beff', lineHeight: 20, fontStyle: 'italic' },
  scenarioCard:     { borderWidth: 1, borderLeftWidth: 3, borderRadius: 10, borderTopLeftRadius: 0, borderBottomLeftRadius: 0, padding: 14, marginBottom: 10, backgroundColor: 'rgba(255,255,255,.02)' },
  scenarioHeader:   { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  scenarioLabel:    { fontSize: 13, fontWeight: '500', color: C.white, flex: 1 },
  scenarioProb:     { fontSize: 14, fontWeight: '700' },
  probBar:          { height: 3, backgroundColor: 'rgba(255,255,255,.06)', borderRadius: 2, marginBottom: 10 },
  probFill:         { height: '100%', borderRadius: 2 },
  debateHeader:     { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 9, flexWrap: 'wrap' },
  debatePill:       { borderRadius: 20, paddingHorizontal: 10, paddingVertical: 3, borderWidth: 1 },
  debatePillText:   { fontSize: 9, fontWeight: '700', letterSpacing: 0.5 },
  debateName:       { fontSize: 12, fontWeight: '500', color: C.white },
  neutralBlock:     { backgroundColor: 'rgba(255,255,255,.02)', borderWidth: 1, borderStyle: 'dashed', borderColor: 'rgba(255,255,255,.1)', borderRadius: 12, padding: 14 },
  bulletRow:        { flexDirection: 'row', gap: 8, marginBottom: 8, alignItems: 'flex-start' },
  bulletDiamond:    { color: C.indigo, fontSize: 9, marginTop: 4 },
  bulletArrow:      { color: C.gold, fontSize: 11, marginTop: 2 },
  tldrBlock:        { backgroundColor: 'rgba(91,79,232,.09)', borderWidth: 1, borderColor: 'rgba(91,79,232,.24)', borderRadius: 12, padding: 14, marginBottom: 12 },
  tldrText:         { fontSize: 13, color: '#c4beff', fontWeight: '500', lineHeight: 21 },
  questionBlock:    { backgroundColor: 'rgba(0,229,176,.06)', borderWidth: 1, borderColor: 'rgba(0,229,176,.2)', borderRadius: 12, padding: 14 },
  errorBlock:       { alignItems: 'center', paddingVertical: 60 },
  errorText:        { color: 'rgba(255,255,255,.35)', fontSize: 13, marginBottom: 16, textAlign: 'center' },
  retryBtn:         { borderWidth: 1, borderColor: 'rgba(91,79,232,.45)', borderRadius: 8, paddingVertical: 10, paddingHorizontal: 22 },
  retryText:        { color: C.indigo, fontSize: 13 },
  litHeader:        { flexDirection: 'row', alignItems: 'flex-start', padding: 16, paddingTop: 14, backgroundColor: C.bg1, borderBottomWidth: 1, borderBottomColor: C.border },
  litCat:           { fontSize: 9, fontWeight: '700', letterSpacing: 1.3, marginBottom: 4 },
  litHeadline:      { fontSize: 13, color: C.white, fontWeight: '500', lineHeight: 19 },
  bmIconBtn:        { padding: 8 },
  bmIcon:           { fontSize: 22, color: 'rgba(255,255,255,.3)' },
  sourceStrip:      { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 16, paddingVertical: 8, backgroundColor: 'rgba(255,255,255,.02)', borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,.05)' },
  sourceText:       { fontSize: 10, color: 'rgba(255,255,255,.32)' },
  tabBar:           { maxHeight: 50, backgroundColor: C.bg },
  tabBtn:           { paddingHorizontal: 16, paddingVertical: 7, borderRadius: 22, borderWidth: 1, borderColor: C.border, backgroundColor: 'rgba(255,255,255,.04)', flexDirection: 'row', alignItems: 'center' },
  tabBtnText:       { fontSize: 12, fontWeight: '500' },
  divider:          { height: 1, backgroundColor: 'rgba(255,255,255,.07)', marginHorizontal: 16, marginTop: 2 },
  bmHeader:         { flexDirection: 'row', alignItems: 'center', padding: 18, paddingTop: 14, borderBottomWidth: 1, borderBottomColor: C.border },
  bmTitle:          { fontSize: 22, fontWeight: '700', color: C.white, letterSpacing: -0.3 },
  bmSub:            { fontSize: 11, color: C.muted, marginTop: 2 },
  emptyState:       { alignItems: 'center', paddingTop: 90 },
  emptyIcon:        { fontSize: 44, color: 'rgba(255,255,255,.18)', marginBottom: 18 },
  emptyTitle:       { fontSize: 16, color: 'rgba(255,255,255,.38)', marginBottom: 8 },
  emptyBody:        { fontSize: 13, color: C.muted, textAlign: 'center', maxWidth: 260, lineHeight: 21 },
  bmCard:           { backgroundColor: 'rgba(255,255,255,.03)', borderWidth: 1, borderColor: C.border, borderLeftWidth: 3, borderRadius: 14, padding: 16, marginBottom: 12 },
  bmCat:            { fontSize: 9, fontWeight: '700', letterSpacing: 1.2, marginBottom: 6 },
  bmHl:             { fontSize: 14, fontWeight: '500', color: C.white, lineHeight: 21, marginBottom: 10 },
  bmMeta:           { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  bmSrc:            { fontSize: 11, color: C.muted },
  bmDeepBtn:        { borderWidth: 1, paddingHorizontal: 12, paddingVertical: 4, borderRadius: 20 },
  bmDeepBtnText:    { fontSize: 11 },
  logoRow:          { flexDirection: 'row', alignItems: 'center', gap: 9 },
  logo:             { fontSize: 21, fontWeight: '900', color: C.white, letterSpacing: 4 },
  savedBtn:         { backgroundColor: 'rgba(255,255,255,.08)', borderWidth: 1, borderColor: 'rgba(255,255,255,.14)', borderRadius: 22, paddingHorizontal: 14, paddingVertical: 8 },
  savedBtnText:     { color: 'rgba(255,255,255,.72)', fontSize: 12 },
  catBadge:         { borderRadius: 22, paddingHorizontal: 12, paddingVertical: 4, borderWidth: 1 },
  catText:          { fontSize: 9, fontWeight: '700', letterSpacing: 1.3 },
});